on:
  push:
    paths:
      - .github/**
      - content/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish DevRel Blox
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Validate Blox Data
        id: build
        uses: devrel-blox/github-action@v0.0.7
        with:
          directory: data

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "blox"
          prerelease: true
          title: "DevRel Blox"
          files: |
            content/out/data.json
